#!/bin/bash

set -e
set -x

if [ $# -ne 3 ]
then
    cat >&2 <<EOUSAGE
Usage: $0 <UNIX-USER> <HOST> <INSTALLATION-DIRECTORY>
EOUSAGE
    exit 1
fi

UNIX_USER="$1"
HOST="$2"
DIRECTORY="$3"
DB_NAME="alaveteli"

# Check that the arguments we've been passed are sensible:

IP_ADDRESS_FOR_HOST="$(dig +short $HOST)"

if [ x = x"$IP_ADDRESS_FOR_HOST" ]
then
    echo "The hostname $HOST didn't resolve to an IP address"
    exit 1
fi

if ! id "$UNIX_USER" 2> /dev/null > /dev/null
then
    echo "The user '$UNIX_USER' didn't exist."
    exit 1
fi

if [ "$(whoami)" != "$UNIX_USER" ]
then
    echo "This script should be run by the user '$UNIX_USER'."
    exit 1
fi

REPOSITORY="$DIRECTORY/alaveteli"
LINK_DESTINATION="$HOME/alaveteli"

ln -sfn "$REPOSITORY" $LINK_DESTINATION
cd "$REPOSITORY"

BASHRC="$HOME/.bashrc"

BASHRC_GEM_COMMENT="Set up local gem directory for Alaveteli"
BASHRC_START="# START $BASHRC_GEM_COMMENT"
BASHRC_END="# END $BASHRC_GEM_COMMENT"

# Remove the old lines we added:
sed -ibackup "/$BASHRC_START/,/$BASHRC_END/d" "$BASHRC"

# Create a temporary file, so we can prepend the lines we need.  They
# need to be prepended since the Ubuntu skeleton .bashrc begins with
# '[ -z "$PS1" ] && return', skipping the rest of the .bashrc for
# non-interactive use, but and we need the gem settings when invoking
# commands in the shell non-interactively.
TMP_BASHRC="$(mktemp "$BASHRC.XXXXXXX")"

cat >>$TMP_BASHRC <<EOBRC
$BASHRC_START
export GEM_HOME="$HOME/gems"
mkdir -p "\$GEM_HOME"
export GEM_PATH=
export PATH="\$GEM_HOME/bin:\$PATH"
$BASHRC_END
EOBRC
fi

cat "$BASHRC" >> "$TMP_BASHRC"
mv "$TMP_BASHRC" "$BASHRC"

source "$BASHRC"

bundle install

# Write sensible values into the config file:

# sed -r \
#     -e "s,^( *MAPIT_DB_NAME:).*,\\1 '$DB_NAME'," \
#     -e "s,^( *MAPIT_DB_USER:).*,\\1 '$UNIX_USER'," \
#     -e "s,^( *COUNTRY:).*,\\1 ''," \
#     -e "s,^( *AREA_SRID:).*,\\1 4326," \
#     -e "s,^( *DJANGO_SECRET_KEY:).*,\\1 '$RANDOM_STRING'," \
#     conf/general.yml-example > conf/general.yml

# Create the database if it doesn't exist:
# if ! psql -l | egrep "^ *$DB_NAME *\|" > /dev/null
# then
#     createdb -T template_postgis --owner "$UNIX_USER" "$DB_NAME"
#     cd $REPOSITORY/project
#     ./manage.py syncdb --noinput
#     ./manage.py migrate mapit
# fi
